from fastapi import APIRouter
# from src.endpoints import oee_analysis_plantwise,downtime_report,login,master_company,master_business_unit,master_plant,master_department,master_shift,master_equipment_group,master_equipment_class,master_processtype,master_equipment,master_downtime_category,master_downtime_subcategory,master_downtime_assignment,master_m4,master_uom,master_uom_mapping,master_rejection_category,master_rejection_subcategory, master_user_level, master_userpage, master_operator, master_equipment_target, master_operation, master_route_fields, master_integrated_linemapping, users, job_route_report_dashboard, speed_log_report, speed_vs_item_report, meter_progress, performence_report, report, downtime_dashboard, defect_dashboard_report
from src.endpoints.report import *
from src.endpoints import login,master_company,master_business_unit,master_department,master_plant,master_equipment_group,master_equipment_class,master_processtype,master_equipment,master_meter,master_shift,master_function,master_model_make,master_operator,master_alarm,master_model,user_rights,load_analysis,sidebar,operations,report,manual_entry,energy_calculation,group_name,order_wise,master_meter_factor,sld,master_holiday,report_fields,master_holiday_type,master_rights,master_meter_mapping,master_meter_group, master_roundoff, users, master_campus, master_source, master_polling_data,master_user_level,master_userpage,master_converter, master_converter_mdl,master_converter_make,master_source_entry,master_budget_entry,master_mail

router = APIRouter()

router.include_router(login.router)
router.include_router(master_company.router)
router.include_router(master_business_unit.router)
router.include_router(master_plant.router)
router.include_router(master_department.router)
router.include_router(master_shift.router)
router.include_router(master_equipment_group.router)
router.include_router(master_function.router)
router.include_router(master_converter.router)
router.include_router(master_equipment.router)
router.include_router(master_meter.router)
router.include_router(master_equipment_class.router)
router.include_router(master_processtype.router)
router.include_router(master_operator.router)
router.include_router(master_alarm.router)
router.include_router(report_fields.router)
router.include_router(master_model.router)
router.include_router(master_model_make.router)
router.include_router(user_rights.router)
router.include_router(load_analysis.router)
router.include_router(sidebar.router)
router.include_router(operations.router)
router.include_router(report.router)
router.include_router(manual_entry.router)
router.include_router(energy_calculation.router)
router.include_router(group_name.router)
router.include_router(order_wise.router)
router.include_router(master_meter_factor.router)
router.include_router(sld.router)
router.include_router(master_holiday.router)
router.include_router(master_holiday_type.router)
router.include_router(master_rights.router)
router.include_router(master_meter_mapping.router)
router.include_router(master_meter_group.router)
router.include_router(master_roundoff.router)
router.include_router(users.router)
router.include_router(master_campus.router)
router.include_router(master_source.router)
router.include_router(master_polling_data.router)
router.include_router(master_userpage.router)
router.include_router(master_user_level.router)
router.include_router(master_converter_make.router)
router.include_router(master_converter_mdl.router)
router.include_router(master_source_entry.router)
router.include_router(master_budget_entry.router)
router.include_router(master_mail.router)

